server:
  port: 8080

spring:
  application:
    name: Test-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/Demodb
    username: postgres
    password: Considerme@2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

